export enum Routes {
  HOME = 'HOME',
  MAP = 'MAP',
  CREATE_EDIT_PLANT = 'CREATE_EDIT_PLANT',
  VISUALIZE_PLANT = 'VISUALIZE_PLANT',
  FAVORITES = 'FAVORITES',
  USER_PROFILE = 'USER_PROFILE',
  SETTINGS = 'SETTINGS',
  EDIT_PROFILE = 'EDIT_PROFILE',
}
